// login action types
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// footer action types
export const TOGGLE_HEART = "TOGGLE_HEART";
export const TOGGLE_COMMENT = "TOGGLE_COMMENT";

//comment tpyes
export const FETCHING_COMMENTS = "FETCHING_COMMENTS";
export const FETCHING_COMMENTS_SUCCESS = "FETCHING_COMMENTS_SUCCESS";
export const FETCHING_COMMENTS_FAIL = "FETCHING_COMMENTS_FAIL";

export const POSTING_COMMENTS = "POSTING_COMMENTS";
export const POSTING_COMMENTS_SUCCESS = "POSTING_COMMENTS_SUCCESS";
export const POSTING_COMMENTS_FAIL = "POSTING_COMMENTS_FAIL";

export const UPDATE_COMMENTS = "UPDATE_COMMENTS";
export const UPDATE_COMMENTS_SUCCESS = "UPDATE_COMMENTS_SUCCESS";
export const UPDATE_COMMENTS_FAIL = "UPDATE_COMMENTS_FAIL";

export const DELETING_COMMENTS = "DELETING_COMMENTS";
export const DELETING_COMMENTS_SUCCESS = "DELETING_COMMENTS_SUCCESS";
export const DELETING_COMMENTS_FAIL = "DELETING_COMMENTS_FAIL";

export const ONUPDATECOMMENT = "ONUPDATECOMMENT";
